import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e1e3e4',
        'on-primary-container': '#75bfa0',
        'surface-container-high': '#e7e8e9',
        tertiary: '#312e1d',
        primary: '#003525',
        'on-secondary-container': '#745c00',
        'secondary-fixed': '#ffe088',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#eae2c9',
        'on-tertiary-fixed-variant': '#4b4734',
        'surface-variant': '#e1e3e4',
        'surface-container-low': '#f3f4f5',
        surface: '#f8f9fa',
        'inverse-surface': '#2e3132',
        background: '#f8f9fa',
        'inverse-primary': '#8bd6b6',
        'on-secondary-fixed-variant': '#574500',
        'tertiary-container': '#484431',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed65b',
        'inverse-on-surface': '#f0f1f2',
        'surface-container': '#edeeef',
        'on-primary-fixed': '#002116',
        'outline-variant': '#bfc9c4',
        'surface-bright': '#f8f9fa',
        error: '#ba1a1a',
        'on-primary-fixed-variant': '#00513b',
        'secondary-fixed-dim': '#e9c349',
        'tertiary-fixed-dim': '#cec6ae',
        secondary: '#735c00',
        outline: '#707975',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#241a00',
        'on-tertiary-fixed': '#1f1c0c',
        'on-surface-variant': '#3f4945',
        'on-tertiary': '#ffffff',
        'primary-container': '#004e38',
        'on-background': '#191c1d',
        'surface-dim': '#d9dadb',
        'primary-fixed': '#a6f2d1',
        'primary-fixed-dim': '#8bd6b6',
        'surface-tint': '#1b6b51',
        'on-surface': '#191c1d',
        'on-tertiary-container': '#b8b199',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      keyframes: {
        pulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.4' },
        },
        fadeIn: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        fadeIn: 'fadeIn 0.4s ease-out forwards',
      },
    },
  },
  plugins: [],
}

export default config
